apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - image: okteto.dev/job:latest
        name: job
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "fed332ac-f94f-4c2d-9677-904461769270"
        - name: Vless_Path
          value: "/v2022"
        - name: Vmess_UUID
          value: "4a552064-80f1-4195-ad8b-10c7220026af"
        - name: Vmess_Path
          value: "/vm2021"
        - name: Share_Path
          value: "/v2link"
