apiVersion: apps/v1
kind: Deployment
metadata:
  name: fly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fly
  template:
    metadata:
      labels:
        app: fly
    spec:
      containers:
      - image: okteto.dev/fly:latest
        name: fly
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "studentaffairs.com"
        - name: Vless_UUID
          value: ""
        - name: Vless_Path
          value: "/v2022"
        - name: Vmess_UUID
          value: ""
        - name: Vmess_Path
          value: "/vm2021"
        - name: Share_Path
          value: "/v2link"
