apiVersion: apps/v1
kind: Deployment
metadata:
  name: fire
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fire
  template:
    metadata:
      labels:
        app: fire
    spec:
      containers:
      - image: okteto.dev/fire:latest
        name: fire
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.bing.com"
        - name: Vless_UUID
          value: "350638d9-3a16-4c17-8ec6-3d1ec77faaf7"
        - name: Vless_Path
          value: "/v2022"
        - name: Vmess_UUID
          value: "47381d0b-f884-4f64-8f94-a0b11c8d0286"
        - name: Vmess_Path
          value: "/vm2021"
        - name: Share_Path
          value: "/v2link"
