apiVersion: apps/v1
kind: Deployment
metadata:
  name: open
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open
  template:
    metadata:
      labels:
        app: open
    spec:
      containers:
      - image: okteto.dev/open:latest
        name: open
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "c6b67c8e-20d2-407b-9f1b-21d3a13b9678"
        - name: Vless_Path
          value: "/v2022"
        - name: Vmess_UUID
          value: "2f9dbd55-e250-4f50-8cf9-10632540d386"
        - name: Vmess_Path
          value: "/vm2021"
        - name: Share_Path
          value: "/v2link"
